export enum Role {
  ADMIN = "ADMIN",
  SUPER_ADMIN = "SUPER_ADMIN",
}

export enum PermissionList {
  CREATE_EMAIL_TEMPLATE = "CREATE_EMAIL_TEMPLATE",
  UPDATE_EMAIL_TEMPLATE = "UPDATE_EMAIL_TEMPLATE",
  DELETE_EMAIL_TEMPLATE = "DELETE_EMAIL_TEMPLATE",
  CREATE_METADATA_PLACEHOLDER = "CREATE_METADATA_PLACEHOLDER",
  UPDATE_METADATA_PLACEHOLDER = "UPDATE_METADATA_PLACEHOLDER",
  DELETE_METADATA_PLACEHOLDER = "DELETE_METADATA_PLACEHOLDER",
  UPDATE_EMAIL_SEND_LOG = "UPDATE_EMAIL_SEND_LOG",
  DELETE_EMAIL_SEND_LOG = "DELETE_EMAIL_SEND_LOG",
  CREATE_EMAIL_PLACEHOLDERS = "CREATE_EMAIL_PLACEHOLDERS",
  UPDATE_EMAIL_PLACEHOLDERS = "UPDATE_EMAIL_PLACEHOLDERS",
  DELETE_EMAIL_PLACEHOLDERS = "DELETE_EMAIL_PLACEHOLDERS",
}

export const ROLES_RANK = [Role.ADMIN, Role.SUPER_ADMIN];

export const ROLE_RIGHTS = new Map();
ROLE_RIGHTS.set(Role.ADMIN, [
  PermissionList.CREATE_EMAIL_TEMPLATE,
  PermissionList.UPDATE_EMAIL_TEMPLATE,
  PermissionList.DELETE_EMAIL_TEMPLATE,
  PermissionList.CREATE_METADATA_PLACEHOLDER,
  PermissionList.UPDATE_METADATA_PLACEHOLDER,
  PermissionList.DELETE_METADATA_PLACEHOLDER,
  PermissionList.CREATE_EMAIL_PLACEHOLDERS,
  PermissionList.UPDATE_EMAIL_PLACEHOLDERS,
  PermissionList.DELETE_EMAIL_PLACEHOLDERS,
]);
ROLE_RIGHTS.set(Role.SUPER_ADMIN, [
  ...ROLE_RIGHTS.get(Role.ADMIN),
  PermissionList.UPDATE_EMAIL_SEND_LOG,
  PermissionList.DELETE_EMAIL_SEND_LOG,
]);
